### ISSUE TITLE
Running 'javah' gives a ProviderNotFoundException

### ISSUE THREAD

**Issue by KasperHesse** [jodersky/sbt-jni#37]
When running `sbt javah` I will sometimes get a java.nio.file.ProviderNotFoundException. If I generate a new project with the same `build.sbt` file and copy it and my .scala files over, the issue does *not* persist. Once the exception shows up, I haven't yet found a way to make it disappear again.

The contents of my build.sbt are as follows:
```
scalaVersion := "2.12.6"
scalacOptions := Seq("-Xsource:2.11")
resolvers ++= Seq(
  Resolver.sonatypeRepo("snapshots"),
  Resolver.sonatypeRepo("releases")
)
libraryDependencies += "org.scalatest" %% "scalatest" % "3.2.0" % "test"
enablePlugins(JniNative)
```

The stack trace when running `sbt javah` is as follows.
```
[info] Compiling 1 Scala source to /home/user/jnitest/target/classes ...
[info] Headers will be generated to /home/user/jnitest/src/native/include
[error] stack trace is suppressed; run last javah for the full output
[error] (javah) java.nio.file.ProviderNotFoundException: Provider not found
[error] Total time: 8 s, completed Sep 25, 2020, 4:01:07 PM
sbt:jnitest> last javah
[info] Headers will be generated to /home/user/jnitest/src/native/include
[error] java.nio.file.ProviderNotFoundException: Provider not found
[error]         at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:423)
[error]         at ch.jodersky.sbt.jni.javah.Utils.classPathRoot(Utils.java:99)
[error]         at ch.jodersky.sbt.jni.javah.ClassPath.<init>(ClassPath.java:16)
[error]         at ch.jodersky.sbt.jni.javah.JavahTask.addClassPath(JavahTask.java:54)
[error]         at ch.jodersky.sbt.jni.plugins.JniJavah$.$anonfun$mainSettings$9(JniJavah.scala:65)
[error]         at ch.jodersky.sbt.jni.plugins.JniJavah$.$anonfun$mainSettings$9$adapted(JniJavah.scala:65)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at ch.jodersky.sbt.jni.plugins.JniJavah$.$anonfun$mainSettings$4(JniJavah.scala:65)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] (javah) java.nio.file.ProviderNotFoundException: Provider not found
```

Do you have any ideas what this could be caused by? I have tried running `sbt clean` to no avail. I guess it's something I'm doing wrong, but for the life of me I cannot figure out what that thing is. Performing a reboot of my PC does not fix the issue.

**Comment by jodersky** [comment]
What's are your OS, java and sbt versions? This looks like its not related to sbt-jni

**Comment by KasperHesse** [comment]
Sorry, should've obviously included that in the initial post.
* OS: Ubuntu 18.04.4 running under WSL on Windows 10 (1909)
* Java: OpenJDK 11.0.6
* sbt: 1.3.8
* Scala: 2.11.12

**Comment by jodersky** [comment]
Hmm, this looks alright. Unfortunately I don't know what it could be. Looking at the error message, I would think it's not related to sbt-jni, but maybe something to do with file system access under WSL.

sbt-jni extracts binaries into a temp file, so maybe that is something that is buggy in WSL. I'd recommend to try this under WSL2 and see if the error persists.
